# 设置字体族
font_family      family="JetBrainsMono Nerd Font Mono"
# 设置字体大小
font_size        10.0
# 设置粗体、斜体字体（通常auto即可）
bold_font        auto
italic_font      auto
bold_italic_font auto

# BEGIN_KITTY_THEME
# Nord
include current-theme.conf
# END_KITTY_THEME

# 初始窗口尺寸（像素）
initial_window_width  1024
initial_window_height 768
# 是否记住窗口大小
remember_window_size   yes
# 窗口内边距（像素）
window_padding_width 10
# 启用哪些布局
enabled_layouts fat, grid, horizontal, vertical, splits

# 新建OS窗口
map ctrl+shift+n new_os_window
# 关闭窗口
map ctrl+shift+w close_window
# 新建标签页
map ctrl+shift+t new_tab
# 下一个标签页
map ctrl+shift+right next_tab
# 上一个标签页
map ctrl+shift+left previous_tab
# 改变布局
map ctrl+shift+l next_layout
# 增大字体
map ctrl+shift+up change_font_size all +2.0
# 减小字体
map ctrl+shift+down change_font_size all -2.0
# 重置字体大小
map ctrl+shift+backspace change_font_size all 0

# 设置背景图片（必须使用绝对路径，且路径中最好无中文或特殊字符）
# background_image ~/wallpaper/7.png
# 设置背景图片布局（scaled-缩放，tiled-平铺，centered-居中）
# background_image_layout scaled
# 设置背景不透明度（0.0完全透明 - 1.0完全不透明）
background_opacity 0.65

# 启用文本合成
enable_text_composition yes

# 设置输入法相关选项
input_method fcitx

# 拖尾
# 启用光标动画轨迹
cursor_trail 10
