# 三指左右滑动 - 切换工作区
gesture swipe left	hyprctl dispatch workspace e-1
gesture swipe right	hyprctl dispatch workspace e+1

# 四指左右滑动 - 切换窗口
gesture swipe left	4	hyprctl dispatch workspace m-1
gesture swipe right	4	hyprctl dispatch workspace m+1
